### ISSUE TITLE
log contaminates global namespace

### ISSUE THREAD

**Issue by 1Hyena** [GreycLab/CImg#389]
My project has a function named `log` in its global namespace.

Because of that, I am unable to use CImg, as CImg seems to have its own use for _log_.

![Screenshot from 2023-07-10 10-34-26](https://github.com/GreycLab/CImg/assets/3479475/6cc1a140-916e-4bfc-8796-8b0020d1c055)

**Comment by dtschump** [comment]
No idea, sorry. Does this compiles when `CImg.h` is not included ?

**Comment by 1Hyena** [comment]
Yes, then it compiles without any problems.

**Comment by dtschump** [comment]
It has to be something to do with `log()` indeed. If I rename `log()` to `log3()` in your example, it compiles.

**Comment by dtschump** [comment]
I have a work-around:
~~~

namespace my_log {
  void log(const char *text) {
    std::cerr << text << "\n";
  }
}

bool deserialize(
    int argc, char **argv,
    const std::function<void(const char *text)>& log_callback
) {
    return true;
}

int main(int argc, char **argv) {
  if (!deserialize(argc, argv, my_log::log)) {
        return EXIT_FAILURE;
    }

    return EXIT_SUCCESS;
}
~~~
but I still don't get why using just `log` doesn't work.

**Comment by 1Hyena** [comment]
Thanks, I changed the name of the function, for now, but in the long term this should be fixed on the library side. Unfortunately I also don't have a clue why this happens. The following lines from CImg.h are suspicious though:

```C++

#define _cimg_create_pointwise_function(name) \
  template<typename T> \
  inline CImg<_cimg_Tfloat> name(const CImg<T>& instance) { \
    return instance.get_##name(); \
  }

  _cimg_create_pointwise_function(sqr)
  _cimg_create_pointwise_function(sqrt)
  _cimg_create_pointwise_function(erf)
  _cimg_create_pointwise_function(exp)
  _cimg_create_pointwise_function(log)
```

**Comment by dtschump** [comment]
Yes, these line actually creates a `log()` function for `CImg<T>` objects, so that a user can do this:
~~~
CImg<> img("filename.bmp");
CImg<> img_log = log(img);
~~~
But removing the line ` _cimg_create_pointwise_function(log)` does not solve the compilation issue.

**Comment by dtschump** [comment]
OK, so I've found the problem. It doesn't come from CImg, but from `cmath`.
Replacing `#include "CImg.h"` by `#include <cmath>` raises exactly the same problem.
(and of course, CImg actually includes `cmath` by default).

**Comment by 1Hyena** [comment]
Interesting. I thought the c prefix headers such as cmath enabled their respective functions via the std namespace. So one would call std::log instead of just log.

**Comment by dtschump** [comment]
In theory yes, but I think `g++` is a bit sloppy about that rule by default, so using `log()` rather than `std::log()` still works.

**Comment by 1Hyena** [comment]
It's unfortunate that such things happen as they are tedious to track down but there's not much we can do about it. It is what it is. I recall having similar issues elsewhere too. Would be great if CImg didn't even include such toxic headers but sometimes it's practically impossible.
